/*
 * Clever API
 * The Clever API
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DistrictStatus
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-17T20:00:26.398Z")
public class DistrictStatus {
  @SerializedName("error")
  private String error = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("last_sync")
  private String lastSync = null;

  @SerializedName("launch_date")
  private String launchDate = null;

  @SerializedName("pause_end")
  private String pauseEnd = null;

  @SerializedName("pause_start")
  private String pauseStart = null;

  @SerializedName("sis_type")
  private String sisType = null;

  /**
   * Gets or Sets state
   */
  @JsonAdapter(StateEnum.Adapter.class)
  public enum StateEnum {
    RUNNING("running"),
    
    PENDING("pending"),
    
    ERROR("error"),
    
    PAUSE("pause");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StateEnum fromValue(String text) {
      for (StateEnum b : StateEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StateEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StateEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StateEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StateEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("state")
  private StateEnum state = null;

  public DistrictStatus error(String error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @ApiModelProperty(value = "")
  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }

  public DistrictStatus id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public DistrictStatus lastSync(String lastSync) {
    this.lastSync = lastSync;
    return this;
  }

   /**
   * Get lastSync
   * @return lastSync
  **/
  @ApiModelProperty(value = "")
  public String getLastSync() {
    return lastSync;
  }

  public void setLastSync(String lastSync) {
    this.lastSync = lastSync;
  }

  public DistrictStatus launchDate(String launchDate) {
    this.launchDate = launchDate;
    return this;
  }

   /**
   * Get launchDate
   * @return launchDate
  **/
  @ApiModelProperty(value = "")
  public String getLaunchDate() {
    return launchDate;
  }

  public void setLaunchDate(String launchDate) {
    this.launchDate = launchDate;
  }

  public DistrictStatus pauseEnd(String pauseEnd) {
    this.pauseEnd = pauseEnd;
    return this;
  }

   /**
   * Get pauseEnd
   * @return pauseEnd
  **/
  @ApiModelProperty(value = "")
  public String getPauseEnd() {
    return pauseEnd;
  }

  public void setPauseEnd(String pauseEnd) {
    this.pauseEnd = pauseEnd;
  }

  public DistrictStatus pauseStart(String pauseStart) {
    this.pauseStart = pauseStart;
    return this;
  }

   /**
   * Get pauseStart
   * @return pauseStart
  **/
  @ApiModelProperty(value = "")
  public String getPauseStart() {
    return pauseStart;
  }

  public void setPauseStart(String pauseStart) {
    this.pauseStart = pauseStart;
  }

  public DistrictStatus sisType(String sisType) {
    this.sisType = sisType;
    return this;
  }

   /**
   * Get sisType
   * @return sisType
  **/
  @ApiModelProperty(value = "")
  public String getSisType() {
    return sisType;
  }

  public void setSisType(String sisType) {
    this.sisType = sisType;
  }

  public DistrictStatus state(StateEnum state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(value = "")
  public StateEnum getState() {
    return state;
  }

  public void setState(StateEnum state) {
    this.state = state;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DistrictStatus districtStatus = (DistrictStatus) o;
    return Objects.equals(this.error, districtStatus.error) &&
        Objects.equals(this.id, districtStatus.id) &&
        Objects.equals(this.lastSync, districtStatus.lastSync) &&
        Objects.equals(this.launchDate, districtStatus.launchDate) &&
        Objects.equals(this.pauseEnd, districtStatus.pauseEnd) &&
        Objects.equals(this.pauseStart, districtStatus.pauseStart) &&
        Objects.equals(this.sisType, districtStatus.sisType) &&
        Objects.equals(this.state, districtStatus.state);
  }

  @Override
  public int hashCode() {
    return Objects.hash(error, id, lastSync, launchDate, pauseEnd, pauseStart, sisType, state);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DistrictStatus {\n");
    
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastSync: ").append(toIndentedString(lastSync)).append("\n");
    sb.append("    launchDate: ").append(toIndentedString(launchDate)).append("\n");
    sb.append("    pauseEnd: ").append(toIndentedString(pauseEnd)).append("\n");
    sb.append("    pauseStart: ").append(toIndentedString(pauseStart)).append("\n");
    sb.append("    sisType: ").append(toIndentedString(sisType)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

