/*
 * Clever API
 * The Clever API
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * DistrictStatus
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-06T11:52:21.984-07:00")
public class DistrictStatus {
  @SerializedName("id")
  private String id = null;

  @SerializedName("sis_type")
  private String sisType = null;

  @SerializedName("state")
  private String state = null;

  @SerializedName("last_sync")
  private String lastSync = null;

  @SerializedName("error")
  private String error = null;

  @SerializedName("pause_start")
  private String pauseStart = null;

  @SerializedName("pause_end")
  private String pauseEnd = null;

  @SerializedName("launch_state")
  private String launchState = null;

  public DistrictStatus id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public DistrictStatus sisType(String sisType) {
    this.sisType = sisType;
    return this;
  }

   /**
   * Get sisType
   * @return sisType
  **/
  @ApiModelProperty(value = "")
  public String getSisType() {
    return sisType;
  }

  public void setSisType(String sisType) {
    this.sisType = sisType;
  }

  public DistrictStatus state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(value = "")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public DistrictStatus lastSync(String lastSync) {
    this.lastSync = lastSync;
    return this;
  }

   /**
   * Get lastSync
   * @return lastSync
  **/
  @ApiModelProperty(value = "")
  public String getLastSync() {
    return lastSync;
  }

  public void setLastSync(String lastSync) {
    this.lastSync = lastSync;
  }

  public DistrictStatus error(String error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @ApiModelProperty(value = "")
  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }

  public DistrictStatus pauseStart(String pauseStart) {
    this.pauseStart = pauseStart;
    return this;
  }

   /**
   * Get pauseStart
   * @return pauseStart
  **/
  @ApiModelProperty(value = "")
  public String getPauseStart() {
    return pauseStart;
  }

  public void setPauseStart(String pauseStart) {
    this.pauseStart = pauseStart;
  }

  public DistrictStatus pauseEnd(String pauseEnd) {
    this.pauseEnd = pauseEnd;
    return this;
  }

   /**
   * Get pauseEnd
   * @return pauseEnd
  **/
  @ApiModelProperty(value = "")
  public String getPauseEnd() {
    return pauseEnd;
  }

  public void setPauseEnd(String pauseEnd) {
    this.pauseEnd = pauseEnd;
  }

  public DistrictStatus launchState(String launchState) {
    this.launchState = launchState;
    return this;
  }

   /**
   * Get launchState
   * @return launchState
  **/
  @ApiModelProperty(value = "")
  public String getLaunchState() {
    return launchState;
  }

  public void setLaunchState(String launchState) {
    this.launchState = launchState;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DistrictStatus districtStatus = (DistrictStatus) o;
    return Objects.equals(this.id, districtStatus.id) &&
        Objects.equals(this.sisType, districtStatus.sisType) &&
        Objects.equals(this.state, districtStatus.state) &&
        Objects.equals(this.lastSync, districtStatus.lastSync) &&
        Objects.equals(this.error, districtStatus.error) &&
        Objects.equals(this.pauseStart, districtStatus.pauseStart) &&
        Objects.equals(this.pauseEnd, districtStatus.pauseEnd) &&
        Objects.equals(this.launchState, districtStatus.launchState);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, sisType, state, lastSync, error, pauseStart, pauseEnd, launchState);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DistrictStatus {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sisType: ").append(toIndentedString(sisType)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    lastSync: ").append(toIndentedString(lastSync)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    pauseStart: ").append(toIndentedString(pauseStart)).append("\n");
    sb.append("    pauseEnd: ").append(toIndentedString(pauseEnd)).append("\n");
    sb.append("    launchState: ").append(toIndentedString(launchState)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

