/*
 * Clever API
 * The Clever API
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Credentials;
import io.swagger.client.model.Location;
import io.swagger.client.model.Name;
import java.util.ArrayList;
import java.util.List;

/**
 * Student
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-27T16:04:29.480-07:00")
public class Student {
  @SerializedName("created")
  private String created = null;

  @SerializedName("credentials")
  private Credentials credentials = null;

  @SerializedName("district")
  private String district = null;

  @SerializedName("dob")
  private String dob = null;

  /**
   * Gets or Sets ellStatus
   */
  public enum EllStatusEnum {
    @SerializedName("Y")
    Y("Y"),
    
    @SerializedName("N")
    N("N"),
    
    @SerializedName("")
    EMPTY("");

    private String value;

    EllStatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("ell_status")
  private EllStatusEnum ellStatus = null;

  @SerializedName("email")
  private String email = null;

  /**
   * Gets or Sets gender
   */
  public enum GenderEnum {
    @SerializedName("M")
    M("M"),
    
    @SerializedName("F")
    F("F"),
    
    @SerializedName("")
    EMPTY("");

    private String value;

    GenderEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("gender")
  private GenderEnum gender = null;

  /**
   * Gets or Sets grade
   */
  public enum GradeEnum {
    @SerializedName("1")
    _1("1"),
    
    @SerializedName("2")
    _2("2"),
    
    @SerializedName("3")
    _3("3"),
    
    @SerializedName("4")
    _4("4"),
    
    @SerializedName("5")
    _5("5"),
    
    @SerializedName("6")
    _6("6"),
    
    @SerializedName("7")
    _7("7"),
    
    @SerializedName("8")
    _8("8"),
    
    @SerializedName("9")
    _9("9"),
    
    @SerializedName("10")
    _10("10"),
    
    @SerializedName("11")
    _11("11"),
    
    @SerializedName("12")
    _12("12"),
    
    @SerializedName("PreKindergarten")
    PREKINDERGARTEN("PreKindergarten"),
    
    @SerializedName("Kindergarten")
    KINDERGARTEN("Kindergarten"),
    
    @SerializedName("PostGraduate")
    POSTGRADUATE("PostGraduate"),
    
    @SerializedName("Other")
    OTHER("Other");

    private String value;

    GradeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("grade")
  private GradeEnum grade = null;

  /**
   * Gets or Sets hispanicEthnicity
   */
  public enum HispanicEthnicityEnum {
    @SerializedName("Y")
    Y("Y"),
    
    @SerializedName("N")
    N("N"),
    
    @SerializedName("")
    EMPTY("");

    private String value;

    HispanicEthnicityEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("hispanic_ethnicity")
  private HispanicEthnicityEnum hispanicEthnicity = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("iep_status")
  private String iepStatus = null;

  @SerializedName("last_modified")
  private String lastModified = null;

  @SerializedName("location")
  private Location location = null;

  @SerializedName("name")
  private Name name = null;

  /**
   * Gets or Sets race
   */
  public enum RaceEnum {
    @SerializedName("Caucasian")
    CAUCASIAN("Caucasian"),
    
    @SerializedName("Asian")
    ASIAN("Asian"),
    
    @SerializedName("Black or African American")
    BLACK_OR_AFRICAN_AMERICAN("Black or African American"),
    
    @SerializedName("American Indian")
    AMERICAN_INDIAN("American Indian"),
    
    @SerializedName("Hawaiian or Other Pacific Islander")
    HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER("Hawaiian or Other Pacific Islander"),
    
    @SerializedName("Two or More Races")
    TWO_OR_MORE_RACES("Two or More Races"),
    
    @SerializedName("Unknown")
    UNKNOWN("Unknown"),
    
    @SerializedName("")
    EMPTY("");

    private String value;

    RaceEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("race")
  private RaceEnum race = null;

  @SerializedName("school")
  private String school = null;

  @SerializedName("schools")
  private List<String> schools = new ArrayList<String>();

  @SerializedName("sis_id")
  private String sisId = null;

  @SerializedName("state_id")
  private String stateId = null;

  @SerializedName("student_number")
  private String studentNumber = null;

  public Student created(String created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(value = "")
  public String getCreated() {
    return created;
  }

  public void setCreated(String created) {
    this.created = created;
  }

  public Student credentials(Credentials credentials) {
    this.credentials = credentials;
    return this;
  }

   /**
   * Get credentials
   * @return credentials
  **/
  @ApiModelProperty(value = "")
  public Credentials getCredentials() {
    return credentials;
  }

  public void setCredentials(Credentials credentials) {
    this.credentials = credentials;
  }

  public Student district(String district) {
    this.district = district;
    return this;
  }

   /**
   * Get district
   * @return district
  **/
  @ApiModelProperty(value = "")
  public String getDistrict() {
    return district;
  }

  public void setDistrict(String district) {
    this.district = district;
  }

  public Student dob(String dob) {
    this.dob = dob;
    return this;
  }

   /**
   * Get dob
   * @return dob
  **/
  @ApiModelProperty(value = "")
  public String getDob() {
    return dob;
  }

  public void setDob(String dob) {
    this.dob = dob;
  }

  public Student ellStatus(EllStatusEnum ellStatus) {
    this.ellStatus = ellStatus;
    return this;
  }

   /**
   * Get ellStatus
   * @return ellStatus
  **/
  @ApiModelProperty(value = "")
  public EllStatusEnum getEllStatus() {
    return ellStatus;
  }

  public void setEllStatus(EllStatusEnum ellStatus) {
    this.ellStatus = ellStatus;
  }

  public Student email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public Student gender(GenderEnum gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  @ApiModelProperty(value = "")
  public GenderEnum getGender() {
    return gender;
  }

  public void setGender(GenderEnum gender) {
    this.gender = gender;
  }

  public Student grade(GradeEnum grade) {
    this.grade = grade;
    return this;
  }

   /**
   * Get grade
   * @return grade
  **/
  @ApiModelProperty(value = "")
  public GradeEnum getGrade() {
    return grade;
  }

  public void setGrade(GradeEnum grade) {
    this.grade = grade;
  }

  public Student hispanicEthnicity(HispanicEthnicityEnum hispanicEthnicity) {
    this.hispanicEthnicity = hispanicEthnicity;
    return this;
  }

   /**
   * Get hispanicEthnicity
   * @return hispanicEthnicity
  **/
  @ApiModelProperty(value = "")
  public HispanicEthnicityEnum getHispanicEthnicity() {
    return hispanicEthnicity;
  }

  public void setHispanicEthnicity(HispanicEthnicityEnum hispanicEthnicity) {
    this.hispanicEthnicity = hispanicEthnicity;
  }

  public Student id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Student iepStatus(String iepStatus) {
    this.iepStatus = iepStatus;
    return this;
  }

   /**
   * Get iepStatus
   * @return iepStatus
  **/
  @ApiModelProperty(value = "")
  public String getIepStatus() {
    return iepStatus;
  }

  public void setIepStatus(String iepStatus) {
    this.iepStatus = iepStatus;
  }

  public Student lastModified(String lastModified) {
    this.lastModified = lastModified;
    return this;
  }

   /**
   * Get lastModified
   * @return lastModified
  **/
  @ApiModelProperty(value = "")
  public String getLastModified() {
    return lastModified;
  }

  public void setLastModified(String lastModified) {
    this.lastModified = lastModified;
  }

  public Student location(Location location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @ApiModelProperty(value = "")
  public Location getLocation() {
    return location;
  }

  public void setLocation(Location location) {
    this.location = location;
  }

  public Student name(Name name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public Name getName() {
    return name;
  }

  public void setName(Name name) {
    this.name = name;
  }

  public Student race(RaceEnum race) {
    this.race = race;
    return this;
  }

   /**
   * Get race
   * @return race
  **/
  @ApiModelProperty(value = "")
  public RaceEnum getRace() {
    return race;
  }

  public void setRace(RaceEnum race) {
    this.race = race;
  }

  public Student school(String school) {
    this.school = school;
    return this;
  }

   /**
   * Get school
   * @return school
  **/
  @ApiModelProperty(value = "")
  public String getSchool() {
    return school;
  }

  public void setSchool(String school) {
    this.school = school;
  }

  public Student schools(List<String> schools) {
    this.schools = schools;
    return this;
  }

  public Student addSchoolsItem(String schoolsItem) {
    this.schools.add(schoolsItem);
    return this;
  }

   /**
   * Get schools
   * @return schools
  **/
  @ApiModelProperty(value = "")
  public List<String> getSchools() {
    return schools;
  }

  public void setSchools(List<String> schools) {
    this.schools = schools;
  }

  public Student sisId(String sisId) {
    this.sisId = sisId;
    return this;
  }

   /**
   * Get sisId
   * @return sisId
  **/
  @ApiModelProperty(value = "")
  public String getSisId() {
    return sisId;
  }

  public void setSisId(String sisId) {
    this.sisId = sisId;
  }

  public Student stateId(String stateId) {
    this.stateId = stateId;
    return this;
  }

   /**
   * Get stateId
   * @return stateId
  **/
  @ApiModelProperty(value = "")
  public String getStateId() {
    return stateId;
  }

  public void setStateId(String stateId) {
    this.stateId = stateId;
  }

  public Student studentNumber(String studentNumber) {
    this.studentNumber = studentNumber;
    return this;
  }

   /**
   * Get studentNumber
   * @return studentNumber
  **/
  @ApiModelProperty(value = "")
  public String getStudentNumber() {
    return studentNumber;
  }

  public void setStudentNumber(String studentNumber) {
    this.studentNumber = studentNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Student student = (Student) o;
    return Objects.equals(this.created, student.created) &&
        Objects.equals(this.credentials, student.credentials) &&
        Objects.equals(this.district, student.district) &&
        Objects.equals(this.dob, student.dob) &&
        Objects.equals(this.ellStatus, student.ellStatus) &&
        Objects.equals(this.email, student.email) &&
        Objects.equals(this.gender, student.gender) &&
        Objects.equals(this.grade, student.grade) &&
        Objects.equals(this.hispanicEthnicity, student.hispanicEthnicity) &&
        Objects.equals(this.id, student.id) &&
        Objects.equals(this.iepStatus, student.iepStatus) &&
        Objects.equals(this.lastModified, student.lastModified) &&
        Objects.equals(this.location, student.location) &&
        Objects.equals(this.name, student.name) &&
        Objects.equals(this.race, student.race) &&
        Objects.equals(this.school, student.school) &&
        Objects.equals(this.schools, student.schools) &&
        Objects.equals(this.sisId, student.sisId) &&
        Objects.equals(this.stateId, student.stateId) &&
        Objects.equals(this.studentNumber, student.studentNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(created, credentials, district, dob, ellStatus, email, gender, grade, hispanicEthnicity, id, iepStatus, lastModified, location, name, race, school, schools, sisId, stateId, studentNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Student {\n");
    
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    credentials: ").append(toIndentedString(credentials)).append("\n");
    sb.append("    district: ").append(toIndentedString(district)).append("\n");
    sb.append("    dob: ").append(toIndentedString(dob)).append("\n");
    sb.append("    ellStatus: ").append(toIndentedString(ellStatus)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    grade: ").append(toIndentedString(grade)).append("\n");
    sb.append("    hispanicEthnicity: ").append(toIndentedString(hispanicEthnicity)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    iepStatus: ").append(toIndentedString(iepStatus)).append("\n");
    sb.append("    lastModified: ").append(toIndentedString(lastModified)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    race: ").append(toIndentedString(race)).append("\n");
    sb.append("    school: ").append(toIndentedString(school)).append("\n");
    sb.append("    schools: ").append(toIndentedString(schools)).append("\n");
    sb.append("    sisId: ").append(toIndentedString(sisId)).append("\n");
    sb.append("    stateId: ").append(toIndentedString(stateId)).append("\n");
    sb.append("    studentNumber: ").append(toIndentedString(studentNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

